

name: Java CI with Gradle

on: [ push,pull_request ]

concurrency:
  group: "latest"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          java-package: 'jdk'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build

      #- name: Remove *-sources.jar
      #  run: rm ./versions/1.20.4/build/devlibs/*-sources.jar || true

      - name: ls1
        run: ls ./versions/1.20.4/build/

      - name: ls2
        run: ls ./versions/1.20.4/build/devlibs
        
      - name: ls3
        run: ls ./versions/1.20.4/build/libs




      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest Build"
          files: |
            ./versions/1.20.4/build/libs/*.jar
